services:
  localstack:
    image: localstack/localstack:latest
    container_name: pismo-eval-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb,dynamodbstreams,iam,sts
    volumes:
      - localstack-data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  localstack-init:
    image: amazon/aws-cli
    container_name: pismo-eval-localstack-init
    volumes:
      - ./localstack-scripts/localstack-init.sh:/init.sh
    entrypoint: ["/bin/sh", "/init.sh"]
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    container_name: pismo-eval-processor
    depends_on:
      - localstack
      - localstack-init
    environment:
        # don't do this in a real environment! mount secrets via a proper method 
        # i.e. mounting to the pod, irsa, ecs task, instance profiles!
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-west-1
      - AWS_ENDPOINT=http://localstack:4566
      - QUEUE_NAME=events
      - DIRECT_DISPATCH=true
      - DELIVER_DLQ_URL=http://localstack:4566/000000000000/deliver-dlq

  deliver:
    build:
      context: .
      dockerfile: Dockerfile.deliver
    container_name: pismo-eval-deliver
    depends_on:
      - localstack
      - localstack-init
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-west-1
      - AWS_ENDPOINT=http://localstack:4566
      - QUEUE_NAME=events
      - ROUTES_TABLE=routes
      - DELIVER_DLQ_URL=http://localstack:4566/000000000000/deliver-dlq

  mock-sink:
    image: hashicorp/http-echo
    command: ["-listen=:8080","-text=OK"]
    ports:
      - "8080:8080"

volumes:
  localstack-data:
